### ISSUE TITLE
Database error when using `get_total_cache_size` with sqlite3

### ISSUE THREAD

**Issue by krayzpipes** [ace-ecosystem/ace2-core#5]
Error observed when running integration tests in CirlceCI. I was also able to reproduce similar issue locally in test: `tests/ace/system/test_caching.py::test_delete_cached_analysis_results_by_mopdule_type[DatabaseACETestSystem]`.

```bash
>       cursor.execute(statement, parameters)
E       sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "(": syntax error
E       [SQL: SELECT count(analysis_result_cache.cache_key) FILTER (WHERE analysis_result_cache.analysis_module_type = ?) AS anon_1 
E       FROM analysis_result_cache]
E       [parameters: ('test_1',)]
E       (Background on this error at: http://sqlalche.me/e/e3q8)
```

Existing call to count cache keys looks like this in `database/caching.py::get_total_cache_size()`:

```python
get_db()
.query(
    func.count(AnalysisResultCache.cache_key).filter(
        AnalysisResultCache.analysis_module_type == amt.name
    )
)
.scalar()
```

This results in the following query:

```sql
SELECT count(analysis_result_cache.cache_key) FILTER (WHERE analysis_result_cache.analysis_module_type = ?) AS anon_1 
FROM analysis_result_cache
```

When I change the query to the following query, the test passes:

```python
get_db()
.query(
    func.count(AnalysisResultCache.cache_key)
).filter(AnalysisResultCache.analysis_module_type == amt.name).scalar()
```

Notice that the `filter` method is called outside of the `.query()` method.

This results in a different query:

```sql
SELECT count(analysis_result_cache.cache_key) AS count_1 
FROM analysis_result_cache 
WHERE analysis_result_cache.analysis_module_type = ?
```
@unixfreak0037  - Is this an okay change to make? I wasn't able to figure out what using the `FILTER` clause buys us since we're only doing the equivalent of one `WHERE` clause in the `get_total_cache_size` function.

**Comment by unixfreak0037** [comment]
Yeah go for it. I was able to reproduce that issue on an Ubuntu 18 build but not on my mac or Ubuntu 20 build. Not sure why yet.
